/* tslint:disable */
/* eslint-disable */
/**
 * tech blog hub site의 API
 * 카테고리, 회사, 검색어를 기반으로 한 검색 API (페이징 지원)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecommendResponseBody
 */
export interface RecommendResponseBody {
    /**
     * 게시글의 요약 텍스트
     * @type {string}
     * @memberof RecommendResponseBody
     */
    'summarizedText': string;
    /**
     * 관련 해시태그 목록
     * @type {Array<string>}
     * @memberof RecommendResponseBody
     */
    'hashtags': Array<string>;
    /**
     * 추천 게시글 목록
     * @type {Array<string>}
     * @memberof RecommendResponseBody
     */
    'recommends': Array<string>;
}

